"""empty message

Revision ID: 43e36edeba00
Revises: 
Create Date: 2020-05-05 03:21:09.713263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e36edeba00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_heavyweight():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_heavyweight():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_authorization():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('username', sa.String(length=120), nullable=False))
    op.drop_constraint('auth_user_name_key', 'auth_user', type_='unique')
    op.create_unique_constraint(None, 'auth_user', ['username'])
    op.drop_column('auth_user', 'name')
    # ### end Alembic commands ###


def downgrade_authorization():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'auth_user', type_='unique')
    op.create_unique_constraint('auth_user_name_key', 'auth_user', ['name'])
    op.drop_column('auth_user', 'username')
    # ### end Alembic commands ###

